/**
 * Provider-neutral metadata contracts for paid PPTX exports.
 *
 * These types deliberately describe metadata only. Patient notes, attachments,
 * generated bytes, card data, provider secrets, and webhook payloads must stay
 * outside the browser and outside Firestore documents exposed to the client.
 */

export const BILLING_SCHEMA_VERSION = 1 as const;

export type BillingCurrency = "IDR" | "USD" | (string & {});

export type OutputStatus =
  | "queued"
  | "rendering"
  | "ready"
  | "failed"
  | "expired";

export type BillingStatus =
  | "not_required"
  | "pending"
  | "paid"
  | "failed"
  | "refunded"
  | "void";

export type BillingLedgerKind = "charge" | "refund" | "reserve" | "release";

export type ProviderName = "stripe" | "xendit" | "midtrans" | "manual" | (string & {});

/** Firestore Timestamp-compatible value without forcing a server SDK on the client. */
export interface FirestoreTimeValue {
  toDate?: () => Date;
  seconds?: number;
  nanoseconds?: number;
}

export interface BillingProductMetadata {
  schemaVersion: typeof BILLING_SCHEMA_VERSION;
  id: string;
  code: string;
  name: string;
  description: string;
  kind: "pptx_export";
  active: boolean;
  priceMinor: number;
  currency: BillingCurrency;
  productVersion: number;
  createdAt: FirestoreTimeValue;
  updatedAt: FirestoreTimeValue;
}

export interface OutputPriceSnapshot {
  productId: string;
  productVersion: number;
  amountMinor: number;
  currency: BillingCurrency;
}

/**
 * User-readable export metadata. The server creates and updates this document;
 * the browser may only read the signed-in user's own output records.
 */
export interface OutputMetadata {
  schemaVersion: typeof BILLING_SCHEMA_VERSION;
  uid: string;
  workspaceId: string;
  templateId: string;
  templateVersion: string;
  slideCount: number;
  status: OutputStatus;
  billingStatus: BillingStatus;
  priceSnapshot: OutputPriceSnapshot;
  idempotencyKey: string;
  provider?: ProviderName;
  paymentReference?: string;
  artifact?: {
    contentType: "application/vnd.openxmlformats-officedocument.presentationml.presentation";
    byteSize: number;
    expiresAt?: FirestoreTimeValue;
  };
  createdAt: FirestoreTimeValue;
  updatedAt: FirestoreTimeValue;
  paidAt?: FirestoreTimeValue;
  completedAt?: FirestoreTimeValue;
  failedAt?: FirestoreTimeValue;
}

export interface BillingSummaryMetadata {
  schemaVersion: typeof BILLING_SCHEMA_VERSION;
  uid: string;
  currency: BillingCurrency;
  paidOutputCount: number;
  refundedOutputCount: number;
  updatedAt: FirestoreTimeValue;
}

export interface BillingLedgerEntryMetadata {
  schemaVersion: typeof BILLING_SCHEMA_VERSION;
  uid: string;
  outputId: string;
  productId: string;
  kind: BillingLedgerKind;
  status: "pending" | "succeeded" | "failed" | "reversed";
  amountMinor: number;
  currency: BillingCurrency;
  provider?: ProviderName;
  providerReference?: string;
  idempotencyKey: string;
  createdAt: FirestoreTimeValue;
  updatedAt: FirestoreTimeValue;
}

/**
 * Internal event index only. Store no raw webhook body or payment credential.
 * The raw event, if needed for reconciliation, belongs in a backend-owned store.
 */
export interface PaymentEventMetadata {
  schemaVersion: typeof BILLING_SCHEMA_VERSION;
  provider: ProviderName;
  providerEventId: string;
  eventType: string;
  processingStatus: "received" | "processed" | "ignored" | "failed";
  signatureVerified: boolean;
  outputId?: string;
  receivedAt: FirestoreTimeValue;
  processedAt?: FirestoreTimeValue;
}

export const billingCollectionPaths = {
  products: "products",
  outputs: (uid: string) => `users/${uid}/outputs`,
  summary: (uid: string) => `users/${uid}/billing/summary`,
  ledger: (uid: string) => `users/${uid}/billing/ledger`,
  paymentEvents: "paymentEvents",
} as const;
